DROP TABLE IF EXISTS user_table;
DROP TABLE IF EXISTS post_table;

CREATE TABLE user_table (
  id SERIAL NOT NULL ,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE post_table (
  id SERIAL NOT NULL,
  author_id INT NOT NULL,
  created TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
  title VARCHAR(256) NOT NULL,
  body TEXT NOT NULL
);